version: '3.8'

services:
  minio:
    container_name: minio-server
    image: quay.io/minio/minio
    command: server /data/mimo --console-address  ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: nest-api
    volumes:
      - ./data/mimo:/data/mimo
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      -  5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres